from tiangolo/uwsgi-nginx-flask:flask-python2.7

RUN pip install flask-restplus

RUN pip install Flask-SQLAlchemy

RUN pip install pandas

RUN pip install markdown

RUN pip install flask-cors

RUN pip install google-cloud-bigquery
RUN pip install google-cloud-storage
