version: "2.1"
services:
  biggim:
      build: "."
      image: "pricelab/translator-bigquery-api"
      ports:
        - "80:80"
        - "443:443"
        - "8080:8080"
      volumes:
        - ./cred:/cred
        - ./app:/app
