name: Behave tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker-compose stack
      run: docker-compose -f docker-compose.ci.yml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Lint with flake8
      run: |
        docker-compose exec -T biggim pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        docker-compose exec -T biggim flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        docker-compose exec -T biggim flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install test requirements
      run: docker-compose exec -T biggim pip install -r test/requirements.txt
    - name: Test with behave
      run: docker-compose exec -T biggim behave test/features
    - name: Check logs
      run: docker-compose logs biggim